package ru.spbpu.frontend;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.event.TableModelListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class ProviderForm extends BaseApplicationForm {

    private JPanel mainForm;
    private JButton toLoginButton;
    private JTabbedPane mainTabPanel;
    private JPanel componentListTab;
    private JPanel orderListTab;
    private JTable componentsTable;

    public ProviderForm(Application app) {
        super(app);
        init();
    }

    private void init() {
        initLoginButton();
        initComponentsTable();
    }

    private void initLoginButton() {
        toLoginButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent mouseEvent) {
                super.mouseClicked(mouseEvent);
                switchToForm(new LoginForm(getApp()));
            }
        });
    }

    private void initComponentsTable() {

        TableModel tableModel = new AbstractTableModel() {
            @Override
            public int getRowCount() {
                return 2;
            }

            @Override
            public int getColumnCount() {
                return 2;
            }

            @Override
            public Object getValueAt(int i, int j) {
                return String.format("%d %d", i, j);
            }
        };
        componentsTable.setModel(tableModel);
    }

    @Override
    JPanel createFormPanel() {
        return mainForm;
    }

    @Override
    String getTitle() {
        return String.format("Main form - %s", getApp().getUserName());
    }

    @Override
    Dimension getSize() {
        final int width = 500;
        final int height = 350;
        return new Dimension(width, height);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainForm = new JPanel();
        mainForm.setLayout(new GridLayoutManager(2, 2, new Insets(10, 10, 10, 10), -1, -1));
        mainForm.setMaximumSize(new Dimension(300, 150));
        mainForm.setMinimumSize(new Dimension(300, 150));
        mainForm.setBorder(BorderFactory.createTitledBorder(""));
        toLoginButton = new JButton();
        toLoginButton.setText("Change user");
        mainForm.add(toLoginButton, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        mainForm.add(spacer1, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        mainForm.add(spacer2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        mainTabPanel = new JTabbedPane();
        mainForm.add(mainTabPanel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        componentListTab = new JPanel();
        componentListTab.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainTabPanel.addTab("Components", componentListTab);
        componentsTable = new JTable();
        componentListTab.add(componentsTable, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        orderListTab = new JPanel();
        orderListTab.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainTabPanel.addTab("Orders", orderListTab);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainForm;
    }
}
